# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160509_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_num', models.IntegerField(default=918015262160L)),
                ('email', models.EmailField(default='shanker4999@gmail.com', max_length=254)),
                ('github', models.CharField(default='https://github.com/shanker4999/', max_length=255)),
            ],
        ),
    ]
