# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(default='', null=True, upload_to=b''),
        ),
    ]
