# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contact_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(default='shan', null=True, upload_to=b''),
        ),
    ]
