# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160512_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='github',
            field=models.CharField(max_length=255),
        ),
    ]
