# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160512_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.AddField(
            model_name='contact',
            name='myaddress',
            field=models.TextField(default='Jharkhand', null=True),
        ),
    ]
