# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='shanker4999@gmail.com', max_length=254),
        ),
    ]
